### ISSUE TITLE
standardize treant state file

### ISSUE THREAD

**Issue by kain88-de** [datreant/datreant#113]
See #100 

It has come up that we need to version and formalize the state file. The state file needs have two sections _common attributes for all treants_ and _attributes for format extensions_.

**Comment by dotsdl** [comment]
Agreed, the docs should include the (very simple) JSON spec for state files. It's not changing anymore and this is useful for packages like MDSynthesis or for external parsing needs.

**Comment by dotsdl** [comment]
No longer needed, since a `Treant` is now defined solely by the presence of a (potentially empty) `.datreant` directory.
