### ISSUE TITLE
Treant.attach won't attach a non tree limb

### ISSUE THREAD

**Issue by richardjgowers** [datreant/datreant#136]
I was reading through the code and [saw this](https://github.com/datreant/datreant.core/blob/develop/src/datreant/core/treants.py#L88):  If you go through the first `KeyError` you won't hit the `self._attach_limb` later on, which I imagine is what is intended.

```python
    def attach(self, *limbname):
        """Attach limbs by name to this Treant.
        """
        for ln in limbname:
            try:
                limb = _TREELIMBS[ln]
            except KeyError:
                try:
                    limb = _LIMBS[ln]
                except KeyError:
                    raise KeyError("No such limb '{}'".format(ln))
            else:
                self._attach_limb(limb)
```

But I'm a little confused on how this method is actually meant to function, I can't figure out how to use it without raising some sort of error?

**Comment by dotsdl** [comment]
Closing, as no longer relevant to 1.0.0.
