### ISSUE TITLE
Article about fast glob functions

### ISSUE THREAD

**Issue by kain88-de** [datreant/datreant#146]
I came across an [article](https://research.swtch.com/glob) talking about the speed of using glob with regular expressions. There is interestingly a different scaling behavior depending on the exact regular expression engine that is used. 

This means a benchmark of the python glob function that tests it's scaling for datreant might be valuable to look at. Or a custom implementation of glob in cython might actually be worth it!

**Comment by dotsdl** [comment]
This is cool, but since we no longer rely on glob hardcodes anywhere within the library (we expose a glob interface in the API, but this must be general), I don't know if it helps us. Closing for now.
