### ISSUE TITLE
Add an aggregator for dataset metadata

### ISSUE THREAD

**Issue by dotsdl** [datreant/datreant#15]
Although HDF5 files are able to store attributes to internal nodes, these are known to be slow to read/write, and there are fundamental size limits to these. What's more, we hope to support more data file backends in the future, so we don't want to rely on the neat features of HDF5 for metadata storage.

If treants had a `.meta` aggregator that worked similarly to the `.data` aggregator, but instead storing dictionaries of python data structures as flat yaml files in the directory structure of the treant, that would be swell. This would allow metadata to live alongside data, whatever its form, and it would be human-readable and editable.

**Comment by kain88-de** [comment]
why don't you add that information to the hdf5 file for the treant? I think it would be very slow to parse hundreds of little yaml files everytime I make a request for data with specific meta-data. (I currently work on around 500+ short trajectories).

**Comment by dotsdl** [comment]
> why don't you add that information to the hdf5 file for the treant? I think it would be very slow to parse hundreds of little yaml files everytime I make a request for data with specific meta-data. (I currently work on around 500+ short trajectories).

Agreed, it wouldn't be performant to store the metadata in yaml files; this would be the cost of having the metadata live next to the data itself in the directory structure and be in a human-readable format.

Storing metadata internally in the Treant's state file is an option, but it does make it harder to manage datasets at the filesystem level, because the metadata associated with a given dataset no longer lives next to the data. Treants currently store nothing about what datasets are present in their tree in the state file, which means that you can move datasets around, delete them, rename the directory tree, etc. without worrying about stale information inside the Treant. What this means is that queries on what data a Treant has will be reliable, but it will always be a bit slow compared to getting tags and categories since it requires querying the filesystem.

I'm a bit inclined to keep the separation between datasets and Treant state that currently exists, but yeah, there are performance costs to this clear separation and flexibility. Perhaps there's a happy middle ground somewhere that *doesn't* open the door to stale state?

**Comment by kain88-de** [comment]
heavy caching and [inotify](https://pypi.python.org/pypi/python-inotify/0.6-test)? I think this should work under osx too, i vaguely remember that the darwin kernel has something similar.

**Comment by dotsdl** [comment]
inotify would require a process to always be listening for these changes; I don't think that would be an easy solution.

**Comment by dotsdl** [comment]
I think this issue is related to things we want to do, but doesn't really address the current route of the library.
