### ISSUE TITLE
Make View and Bundle immutable?

### ISSUE THREAD

**Issue by dotsdl** [datreant/datreant#154]
Currently, the two collection objects in `datreant.core`, `View` (for `Tree`s and `Leaf`s) and `Bundle` (for `Treant`s) are mutable. Members can be added and removed, and the order of these members in these set-like objects can be changed. Is it really necessary that they be mutable? If there isn't much of a case in which mutability is taken advantage of, it would make these objects simpler and hashable if we could make them immutable.

Thoughts?

**Comment by richardjgowers** [comment]
I think it makes more sense for them to be immutable, and for operations (add/subtract etc) to return a new version of the object (similar to dataframes).

**Comment by dotsdl** [comment]
Although not technically immutable (since they are backed by lists internally), `View` and `Bundle` are now immutable from their public interfaces. Closing.
