### ISSUE TITLE
UnboundLocalError in _getselection

### ISSUE THREAD

**Issue by kaceyreidy** [datreant/datreant#175]
If fits is not defined, an UnboundLocalError is raised.

https://github.com/datreant/datreant/blob/b12e875090391502d8c41e8e22a882aca465ec04/src/datreant/metadata.py#L80

The method would function better with the addition of an else statement (and changing second if to elif).

**Comment by dotsdl** [comment]
Thanks @kaceyreidy! Having a look now.
