### ISSUE TITLE
make release 1.0.3 with latest bug fixes

### ISSUE THREAD

**Issue by orbeckst** [datreant/datreant#178]
Can we have a 1.0.3 please with bug fixes?

**Comment by orbeckst** [comment]
Or probably rather a 1.1.0 as there seem to be new features in the commit history — @dotsdl @kain88-de ?

**Comment by dotsdl** [comment]
Can do. Added to schedule for Saturday. Thanks @orbeckst!

**Comment by dotsdl** [comment]
New release is up on PyPI! `conda-forge` will automatically pick up on this and will create a PR updating the conda recipe within a few hours or so.

**Comment by dotsdl** [comment]
Thank you for the friendly nudge @orbeckst!
