### ISSUE TITLE
treant names cannot contain dots '.'

### ISSUE THREAD

**Issue by orbeckst** [datreant/datreant#24]
If I use a name like `A.B.C.D` for a treant then sooner or later I get an 
```
KeyError: B
```

I should be able to use pretty much any character (maybe except '/' or perhaps ':' (whatever really `os.sep` is)).

**Comment by dotsdl** [comment]
This is now fixed; now the Treant's uuid, which is determined in a single place (its state filename) is given by splitting that filename alone, not the full path.
