### ISSUE TITLE
Use pylint to de-lint codebase

### ISSUE THREAD

**Issue by dotsdl** [datreant/datreant#27]
I ran `py.test --pylint` on `datreant` today, and I think there's a large number of elements it pointed out that could be improved. However, it's a bit of a task, and so we should probably figure out which recommendations we wish to follow and which to ignore.

**Comment by kain88-de** [comment]
Did you check what autopep8 or yapf do on the codebase

**Comment by dotsdl** [comment]
I used autopep8 on it a long time ago, when I first added `--pep8` to the `py.test` call on Travis to help clean things up. Since this is still part of the tests, the code style is pretty clean. Where `pylint` appears to complain is some import impropriety, perhaps some code points that look a bit too repeated, etc. I didn't look too deeply at its complaints, but there were a ton of them.

I'll have to try out `yapf` to see what it gives.
