### ISSUE TITLE
Change package to `datreant.core`?

### ISSUE THREAD

**Issue by dotsdl** [datreant/datreant#35]
My broader vision for `datreant` is for it to provide core objects (`Treants`) for pythonic [manipulation of directory trees](https://github.com/datreant/datreant/issues/23) containing many files, along with objects that help with working on aggregations of these objects (`Bundle`). Other modules, such as [`datreant.data`](https://github.com/datreant/datreant.data) provide extended functionality to these objects upon import, but may require specialized dependencies. Meanwhile, domain-specific packages like [`MDSynthesis`](https://github.com/datreant/MDSynthesis) come batteries-included, with all the `datreant` submodules needed to provide the user experience they seek to give, plus whatever else.

So, in order for this to technically work, there cannot be a `datreant` module per-se. Instead, `datreant` must be made to be a namespace-module, which on import cannot really contain anything. What is currently `datreant` must be moved to a sub-module, such as `datreant.core`.

Before making this move, I think some debate is warranted. Thoughts? If no one end up minding, I'll go ahead and make it happen.

**Comment by kain88-de** [comment]
I thought a little bit about you idea of datreant behaving differently depending on the loaded packages.

```python
import datreant.core as dtr
import datreant.data

d = dtr.Treant('data')
```

I'm not really convinced by it. I'm not sure but I think this makes the order of imports important.  That could lead to subtle bugs. When I do a quick script there is a good chance for me to mix this up.
Instead I would prefer a more explicit approach.

```python
import datreant.core as dtr
import datreant.data

d = dtr.Treant('data', data_backend=datreant.data)
# or
d = dtr.Treant('data', data_backend=[datreant.data.npz, datreant.data.hdf5])
# or
d = dtr.Treant('data', data_backend={'array-like': datreant.data.npz, 
                                     'pandas.Dataframe': datreant.data.hdf5})
``` 

That way I can also create different Treant objects with other data_backends or one with a combination.  In the last option you specifiy which backend to use for each data-type.

**Comment by dotsdl** [comment]
The order of imports shouldn't matter, but you're right that depending on the contents of a package, that could change how `Treants` behave in destructive ways. But that can happen with any package really, right?

What I think is important for packages like `datreant.data` is to still keep things as convenient as possible without breaking, and one of these would be to make the core objects available from that namespace. So you could do

```python
from datreant.data import Treant

d = Treant('data')
```
and work as usual. What's happening within `datreant.data` is that it's just modifying the `datreant.Treant` class itself, not subclassing it, attaching only an additional property to it.

I hadn't thought of making `Treant.data` a general-purpose data storage backend that's customizable as you laid out, though. That's worth thinking about on its own, though. Hmm....

**Comment by kain88-de** [comment]
> But that can happen with any package really, right?

theoretically yes. Practically almost never

 

> and one of these would be to make the core objects available from that namespace. So you could do

Ah OK then I misunderstood you earlier/ So the `datreant.core` package by itself is almost always useless.  One is expected to subclass it's `Treant` class and add it's own file-storage system. And we happen to provide a generic `data` one to store hdf5 and npz files. Ok that is nice.

So then for example meteorologists could develop their own package called `datreant.weather` that stores data in their native `netcdf4` format container?

**Comment by dotsdl** [comment]
> Ah OK then I misunderstood you earlier/ So the datreant.core package by itself is almost always useless.

As a package you would import for doing work interactively, effectively yes. It really just keeps to the theme of directory tree manipulation, which other subpackages can make full use of expecting it to be there. Your idea of accessing subtrees and getting views as a collection of these would also be part of this core.

> One is expected to subclass it's Treant class and add it's own file-storage system.

Depending on how domain-specific one wants to get, yeah. This is the approach taken by MDSynthesis, which tacks a whole slew of things onto the base `Treant` and stores more information in its state file. Generally `datreant` subpackages would just provide additional limbs that wouldn't ever need to touch the state files, keeping things clean. In this way subpackages only ever enhance functionality but don't break the base object if they ever disappear or fall into disrepair.

> And we happen to provide a generic data one to store hdf5 and npz files. Ok that is nice.

Yes. :D

The `datreant.data` package also serves as a useful example of this structure. And if later some other interface for handling the same kinds of objects and serializing them becomes more popular or more useful, `datreant.data` itself doesn't have to change. It can remain simple, if that's what's desired.

> So then for example meteorologists could develop their own package called datreant.weather that stores data in their native netcdf4 format container?

Yes. Since different fields have different needs when it comes to file formats, the lowest common denominator is that these still live in a filesystem. Limbs or `Treant` subclasses can be built to address domain-specific needs.

**Comment by dotsdl** [comment]
I'm aware that packages can become so general as to become useless, but I think this kind of structure allows lots of cakes to be had *and* eaten. I know, however, that this isn't the first project to split itself into several semi-independent pieces. Even though it presents its own challenges I think it makes sense here.

**Comment by dotsdl** [comment]
There are a couple alternatives to this:

1. The namespace module that allows separate packages to live in the namespace of datreant could itself be a submodule of datreant, such as `datreant.ex`. Then what's currently in `datreant` doesn't have to move anywhere, but things like `datreant.data` would need to go in `datreant.ex.data`.

2. Avoid namespaces modules entirely by using a naming convention. What's currently billed as `datreant.data` could become `dtrdata` or something similar.

I'm still partial to making `datreant` a namespace module and `datreant.core` the core meat of it, as laid out previously.

**Comment by dotsdl** [comment]
If there are no further thoughts on this, I'm going to proceed with making this package `datreant.core` and finish the necessary work to make `datreant` work as a namespace module. This will also mean that [`datreant.data`](https://github.com/datreant/datreant.data) becomes a separate package, and is [removed from `datreant.core`](https://github.com/datreant/datreant/pull/33).

**Comment by kain88-de** [comment]
Sorry for not answering that quick I'm busy at work right now.

I understand a bit better now what you. But to be sure I would like to have some examples how users
should use datreant in the end.

Creating a Treant then would be.

```python
import datreant.data

obs = datreant.data.Treant('folder')
obs.add('awesome-data') = np.random.randint((100, 100))
```

Would this Treant then only be readable by the `datreant.data` module?  Assume we open the same Treant as above with a `datreant.weather` package?

```python
import datreant.weather

obs = datrant.data.Treant('folder')
obs.add('warm-rain') = weather.data.type((100, 100, 100))
```

I assume that should/will work without a problem. But now this Treant contains objects constructed with different `datreant` sub-packages. What would now happen with

```python
import datreant.data

obs = datrant.data.Treant('folder')
rain = obs.add('warm-rain')
```

Is this supposed to work? Should it fail?

**Comment by kain88-de** [comment]
Btw why do you want to have datreant as a pure namespace package? What other modules besides `datreant.data` do you plan to create in the future. I see that people might want to build stuff on top of datreant.core but with their own name like MDSynthesis. What would possible live under the datreant-umbrella as well, note as a user I would also expect all packages under the datreant-umbrella to work seamlessly together.

**Comment by dotsdl** [comment]
Creating a Treant would be:

```python
import datreant.data

obs = datreant.data.Treant('folder')
```
But adding data would look like, as it does now:

```python
obs.data['awesome-data'] = np.random.randint((100, 100))

# or alternatively
obs.data.add('awesome-data', np.random.randint((100, 100)))
```

> Would this Treant then only be readable by the datreant.data module? Assume we open the same Treant as above with a datreant.weather package?

No, it will always work as a `Treant`, no matter which submodule's namespace the `Treant` class is accessed from. What it won't have is the `Treant.data` property, unless `datreant.data` is imported somewhere. So this means that the `Treant` may have data stored in `pdData.h5`, `npData.h5`, and `pyData.pkl` files which `Treant.data` recognizes, but it won't have that interface component to directly work with them.

In short, things like `datreant.data`, `datreant.xray`, `datreant.blaze`, or any other submodules that add `Limb`s to `Treant`s only ever add functionality when imported, but the base object will always work with its state file and directory/file tree.

I think `datreant.weather` may be a poor example, since climate science folks would more likely build a package akin to MDSynthesis that includes a `Treant` subclass like `Sim` that provides a lot of specific functionality. But something more generally useful and close to what you suggest, like `datreant.xray`, could add a `Treant.xray` limb that gives conveniences for working with netCDF files.

So submodules like `datreant.data` and `datreant.xray` should not add limbs that conflict with other submodules, using unique enough names to avoid this. The problem you describe which amounts to a namespace clash should never happen.

**Comment by dotsdl** [comment]
> Btw why do you want to have datreant as a pure namespace package? What other modules besides `datreant.data` do you plan to create in the future. I see that people might want to build stuff on top of datreant.core but with their own name like MDSynthesis. What would possible live under the datreant-umbrella as well, note as a user I would also expect all packages under the datreant-umbrella to work seamlessly together.

See above. I think this kind of structure, in which `datreant`'s core isn't tied to specific file formats (like HDF5) or specific ways of accessing them (like PyTables, whose future is frankly a bit uncertain), allows it to be relevant for the future and easier to maintain. 

The landscape of tools for data storage and access is rapidly changing. Packages like [blaze](http://blaze.pydata.org/),  [xray](https://github.com/pydata/xarray), [castra](https://github.com/blaze/castra), etc. are all exploring different schemes for storage and data access, and all of them are moving targets at the moment. But by keeping the core light and general, it's possible to experiment with interfaces to these new schemes without having to worry about bloat or stability of the packages being interfaced. It's easier to have *experimental packages* than to have *experimental parts of packages with heavy and perhaps unstable dependencies*.

To be specific, I am interested in working on `datreant.blaze` or `datreant.dask` in the near future, which would add convenience properties for manipulating `blaze` and `dask` objects from their persistent form on disk. I don't have a clear idea for these yet, but that's why I think the room for play is needed.

We can of course do all this without a namespace package, but then we fall back to a naming convention.

**Comment by kain88-de** [comment]
OK yes with what you want to do the namespace package is ok if the `Treant` class is supposed to be changed once you import `datreant.data` or `datreant.xray`.  The way you propose to use the `Treant` objects is also ok since the limbs will only be accessible once the correct modules are imported.

That is fine but I see potential for hard to find bugs. For example we need to have tests that test all possible combinations of limb attachments to the core once we have more then just `data`. 

For personal taste. I don't like that an import of one module (`datreant.data`) changes the behavior of another module (`datreant.core`).  I would feel better if imported modules are always treated as immutable. A solution that is more explicit would be to pass the limbs to the treant object when they are  constructed. This way the class `Treant` would never be changed but instances of it can be different.

```python
import datreant
import datreant.data as dtr_data
import datreant.xray as dtr_xray

datreant.Treant(folder, limbs=[dtr_data, dtr_xray])
```

This is very similar to your approach but the limbs of a Treant object would be explicit instead of implicitly depending on the used imports.

**Comment by kain88-de** [comment]
Using my explicit approach could also have an advantage for package development like MDAnalysis. With your approach it is hard to detect if the removal of a package will break functionality (no static analysis can do that here for python). When a Treant doesn't have the desired limb I have to check the while file and possible other modules for the import. I always have to check if the file in which the function creating the Treant is defined has all the necessary imports.

An explicit solution for the limb attachment like I suggest wouldn't have that problem. When a Treant doesn't have the limb I want/need right now I can easily check the initialization line to see if it should be there.

It would even be very straight forward to create MDAnalysis Treant and attach more limbs to them if the user would want to. We just need to pass them along as arguments.

------------------

Sorry when I sound pessimistic about your idea. I'm just trying to think of possible problems now before you spend a lot of work on it.

**Comment by dotsdl** [comment]
> Sorry when I sound pessimistic about your idea. I'm just trying to think of possible problems now before you spend a lot of work on it.

This kind of discussion is exactly what I wanted, so no worries. The last thing I want is to introduce major pain points that could have been avoided with more careful thought. Thanks for putting so much thought into this. :D

> That is fine but I see potential for hard to find bugs. For example we need to have tests that test all possible combinations of limb attachments to the core once we have more then just data.

Hmmm...true, although in practice if these modules limit themselves to attaching `Limb`s then things should work just fine. Where it does get stickier is for packages like MDSynthesis, which make subclasses of `Treant` with what amount to their own sets of specialized `Limb`s. Ensuring these don't conflict with any other subpackages is not an easy technical problem to solve.

> This is very similar to your approach but the limbs of a Treant object would be explicit instead of implicitly depending on the used imports.

I think explicit is generally better, but I wonder if in practice this can get a bit clunky? What's worse is that something like `datreant.data` doesn't just attach the `Treant.data` limb, but also `Bundle.data`/`Group.members.data`. Each instance of these objects would have to have something like `limbs=` with all the included limbs in their init, and/or a method call after the fact to make the attachment.

Perhaps one way around this is to make an import like `import datreant.data.attach` which has the effect of implicit attachment like I'm pushing for? This reminds me of the behavior of `seaborn`, in which you can do `import seaborn.apionly` to import seaborn **without** it modifying `matplotlib`'s config, whereas `import seaborn` does make those kind of (perhaps destructive, depending on your view) modifications to the environment.

> I always have to check if the file in which the function creating the Treant is defined has all the necessary imports.

It does get confusing, although the modifications to the classes will only ever happen **once**, and once they do happen anywhere in a codebase through something like `import datreant.data` then all `Treant`s have that limb for the rest of the session. This **shouldn't** be a problem, but I understand that it could also lead to some really weird bugs that I have a hard time imagining *a priori*.

 > An explicit solution for the limb attachment like I suggest wouldn't have that problem. When a Treant doesn't have the limb I want/need right now I can easily check the initialization line to see if it should be there.

I think this can work as you stated. I think you sold me on it. :P

Can you think of any showstoppers with `datreant.data.attach` like above for the interactive and lazy user (like myself)?

**Comment by dotsdl** [comment]
Do @richardjgowers , @cing , or @orbeckst see any problems that we haven't engaged with?

**Comment by kain88-de** [comment]
> I think explicit is generally better, but I wonder if in practice this can get a bit clunky? What's worse is that something like datreant.data doesn't just attach the Treant.data limb, but also Bundle.data/Group.members.data. 

Actually I have no idea how the Bundle/Group stuff works right now. I never got them working and the docs on them are not really existing (at least in readthedocs). So as a quick refresher what is the difference between a Bundle and a Group. Also just by the name of it I would expect Bundle be constructed from a set of Treants like `bundle = Bundle(Treant1, Treant2, Treant3)`.

> Perhaps one way around this is to make an import like `import datreant.data.attach` which has the effect of implicit attachment like I'm pushing for?

That sounds better as a non default option. It would also allow you to give the implicit attachment a more thorough testing in your own scripts. Plus packages that use datreant would use the explicit approach as a best practice.

> It does get confusing, although the modifications to the classes will only ever happen once, and once they do happen anywhere in a codebase through something like import datreant.data then all Treants have that limb for the rest of the session. This shouldn't be a problem, but I understand that it could also lead to some really weird bugs that I have a hard time imagining a priori.

So I'm not sure if modification is only once. How are things treated with submodules. So lets say you have a file `a.py` which loads `datreant` and `datreant.data`. Then a file `b.py` imports from `a.py`. I can think of 3 potentially problematic cases with the implicit attachment.

```python
from a import datreant
import datreant.data
```

```python
from a import *
import datreant.data
```

```python
import a
import datreant

d = datreant.Treant
d.data  # will this fail?
```

**Comment by richardjgowers** [comment]
I'm not sure if there's something I've missed, but why can't the vanilla (the most stripped down version) `Treant` live in the top namespace?

**Comment by orbeckst** [comment]
I read the discussion but lack the real insight to say something meaningful about implicit vs explicit attachment of limbs. However, I wouldn't mind a name space such as `datreant.storage` that collects `datreant.storage.hdf5` (rename the too-generic `data`), `datreant.storage.blaze`, `datreant.storage.xray`, `datreant.storage.dask`, `datreant,storage.quipu`, ... It works well from a semantic point of view.

**Comment by dotsdl** [comment]
@richardjgowers in order for namespace packages to actually work, the top-level namespace can't contain anything on its own. If one tries to import `datreant.data` but the module `datreant` also exists and has its own `__init__.py`, if `datreant.data` isn't found within that tree (which it won't be if it's a separate package), it won't be found by the import system, even if it is installed somewhere. Well, this isn't quite true: *sometimes* `datreant.data` will be found, bu that's only if the import system doesn't stumble upon `datreant` first when it traverses the paths in `sys.path`.

Here's a primer I thought was most clear of those out there: http://chimera.labs.oreilly.com/books/1230000000393/ch10.html

**Comment by dotsdl** [comment]
> Actually I have no idea how the Bundle/Group stuff works right now. I never got them working and the docs on them are not really existing (at least in readthedocs).

Yeah, these aren't well documented at the moment. :/

> So as a quick refresher what is the difference between a Bundle and a Group. Also just by the name of it I would expect Bundle be constructed from a set of Treants like `bundle = Bundle(Treant1, Treant2, Treant3)`.

A `Bundle` can be constructed exactly as you describe, and it works as an ordered set of `Treant`s it has as members. `Group.members`, which is a `Limb` that `Group`s have giving aggregate access to members, predated `Bundle`, but works in exactly the same way as `Bundle` does. The distinction is that `Group.members`'s information is persisted in the `Group`'s state file, whereas a `Bundle` exists solely in memory and is non-persistent.

`Group.members` and `Bundle` share the same codebase in [collections.py](https://github.com/datreant/datreant/blob/develop/datreant/collections.py#L22), and they can attach `Limb`s of their own. There is the [`MemberData`](https://github.com/datreant/datreant.data/blob/develop/src/datreant/data/limbs.py#L14) `Limb` that works as an aggregator of datasets from all members.

> That sounds better as a non default option. It would also allow you to give the implicit attachment a more thorough testing in your own scripts. Plus packages that use datreant would use the explicit approach as a best practice.

I agree. I think this keeps it clean, while making interactive work less painful.

> So I'm not sure if modification is only once. How are things treated with submodules. So lets say you have a file a.py which loads datreant and datreant.data. Then a file b.py imports from a.py. I can think of 3 potentially problematic cases with the implicit attachment.

All three of those should work, since AFAIK imports of a module here and there only create names that point to the module object that was generated, of which there is only ever one. Meaning, the first time the interpreter encounters an `import datreant`, no matter where else another one happens only one `module` object gets constructed, and subsequent imports only serve as references to it. So then doing `import datreant.data` anywhere will always result in `Treant` getting a `data` property.

**Comment by dotsdl** [comment]
@orbeckst I like that. It's a bit verbose, but it also points out that these packages provide additional storage/retrieval mechanisms (which all my existing proposals happen to be).

**Comment by dotsdl** [comment]
Okay, so here's a firmed-up proposal to work with; we'll see if we've missed something:

1. The top-level package will remain `datreant`, so that
    ```python
    import datreant as dtr
    t = dtr.Treant('sprout')
    ```
    just works. However, the core `Treant` object is limited to general-purpose tree operations on its internal directory/file structure, and has no specialized interfaces for data storage.

2. Packages like `datreant.data` that provide `Limb`s to `Treant`s and other objects will exist in the `datreant.ex` namespace, so we can eventually have
    ```python
    import datreant as dtr
    import datreant.ex.data
    import datreant.ex.blaze

    t = dtr.Treant('sprout', limbs=[datreant.ex.data, datreant.ex.blaze])
    ```
    which in this case would add give `Treant.data` and `Treant.blaze` `Limb`s to this particular `Treant` instance. No modification of the `Treant` class is made.

3. Modules that provide `Limb`s can add these directly to the `datreant` classes with e.g. `import datreant.ex.data.attach`. So then doing
    ```python
    import datreant as dtr
    import datreant.ex.data.attach

    t = dtr.Treant('sprout')
    ```
    will give a `Treant` with a `data` `Limb`. This means that modules don't have to be specified on a per-instance basis for `Limb` attachment but will already be present, which is convenient for interactive work.

**Comment by dotsdl** [comment]
I think we're close to a satisfying resolution. Anything in this proposal that could be done better?

**Comment by cing** [comment]
I appreciate all the thought that went into this! I'm all for the firmed-up proposal and don't see any improvements to add. Make it so?

**Comment by kain88-de** [comment]
@dotsdl give me a day or two to think possible problems ;)

Also why don't you split up the datapackage as well as @orbeckst suggested? Right now it takes all kinds of objects and stores everything? in hdf5? With the other extensions you have to pass in the correct objects (blaze only will consume blaze objects).

**Comment by dotsdl** [comment]
@cing I think we might have something pretty sweet here; once we appear to have consensus, we'll be off to the races with implementation. :D

**Comment by dotsdl** [comment]
@kain88-de 

No prob. As for the datapackage, I think we're fine with leaving it as it is. Even though its name is super generic, it is also very useful, and its existence won't conflict with other `Limb` packages anyhow. I think this is one of the advantages of this somewhat federated approach to extensions: we don't need to worry too much about a particular extension package being a bit weird, since we can always make others that are thought out differently. The worst that happens is that a name is already taken, in this case `data`.

Do you agree? I'm also fine with scrapping the datapackage and building something better. It really is a bit hacked together and could probably achieve the same convenience with a much better design.

**Comment by dotsdl** [comment]
Also, I think making the namespace package `datreant.ex` is a good catchall name that goes beyond just storage. I can imagine making a `datreant-git` package that gives an `Limb` like `Treant.git` for python version control of a Treant's tree. That's not really a storage scheme, but it does fit into the directory tree model of the package.

**Comment by orbeckst** [comment]
On 17 Jan, 2016, at 11:20, David Dotson wrote:

> Also, I think making the namespace package datreant.ex is a good catchall name that goes beyond just storage. I can imagine making a datreant-git package that gives an Limb like Treant.git for python version control of a Treant's tree. That's not really a storage scheme, but it does fit into the directory tree model of the package.

Just for the record, I dislike short package names that don't tell me what they contain. Given that you can always do an `import as` I see little reason for being to terse.

**Comment by kain88-de** [comment]
I think your proposal to proceed is good. I assume you will still need to figure out a lot along the way but it will be nicely usable. 

Because of the Groups/Bundles (I would call them forests ;))

> A Bundle can be constructed exactly as you describe, and it works as an ordered set of Treants it has as members. Group.members, which is a Limb that Groups have giving aggregate access to members, predated Bundle, but works in exactly the same way as Bundle does. The distinction is that Group.members's information is persisted in the Group's state file, whereas a Bundle exists solely in memory and is non-persistent.

Why the distinction? From a usage perspective I bet they are the same. Why don't you combine them? If a location to save things is given on construction the state will be saved on disk otherwise it will be only in memory. If the code is to different then the anonymous ( previous in-memory objects )could have a statefile in a temporary folder.  

> Group.members and Bundle share the same codebase in collections.py, and they can attach Limbs of their own. There is the MemberData Limb that works as an aggregator of datasets from all members.

Just for collecting data and being able to access all the treants in the forest (Bundle/Group) they shouldn't need any additional limbs, at least the memberdata limb just looks like it is doing that. A forest should be able to access limbs of treants without needing extra limbs of it's own. The access syntax could look like this.

```python
forest = Forest(Treant1, Treant2)
forest.aggregate(limb='data', key='distances-*')
# or
forest.aggregate.data(key='distances-*')
```

I'm not sure if that still fits in here or if it should go into another discussion

A bit unrelated thing. What should happen in a forest if two treants have the same key?

**Comment by dotsdl** [comment]
Although I don't disagree, I think excessive use of `import ... as` can make a lot of code confusing? The reason why `import numpy as np` is acceptable these days in library code is because it's basically a de-facto standard. Not all packages can claim this, though.

Alternatively there's `from datreant.ex import ...`, but this has the problem that if you do:

```python
from datreant.ex import blaze
```
then this can easily get confused with the *actual* `blaze` package, in both reading the code and with an import. I'd rather keep the full name a bit terse than rely on ambiguous shortenings.

**Comment by dotsdl** [comment]
@kain88-de 

`Group` is a `Treant`, and can do anything the base `Treant` class can. The only difference is that it has a `members` `Limb` that stores `Treant` identifiers + locations in the `Group`'s state file. 

In practice I use these objects as conveniences for regularly getting to a bunch of `mdsynthesis.Sim`s that live all over the filesystem, without having to grab them all manually. The `Group` also serves as a clear place for storing data that is strictly aggregate to these `Sim`s; that is, data that comes from the collection of `Sim`s as a whole.

I think the object works, and doubles as an example for subclassing `Treant`, but I do think that there may be alternative (and better) ways to get the same kind of functionality. By contrast, a `Bundle` has no tags, categories, or place in the filesystem. A `Bundle` at present is not a `Treant` at all, but works with collections of them.

At the moment on the `develop` branch the below all works:
```python
import datreant as dtr

g = dtr.Group('forest')

# a Group is a Treant, so it has builtin tags, categories
g.tags.add('stooges', 'losers')
g.categories['nyuknyuk'] = False

# a group stores members, and has some capability to find them if they move
g.members.add([dtr.Treant(x) for x in ('moe', 'larry', 'curly')])

for member in g.members:
    member.data['luck'] = pd.Series(np.random.randn(1000))

# groups can store data, and members.data gives builtin aggregation convenience
g.data['aggregate luck'] = g.members.data['luck'].sum()

# slicing members gives a Bundle
b = g.members[1:]

# Bundle has the same data limb as members for aggregation convenience
b.data['luck'].sum()

# slicing a Bundle gives a Bundle
b[:1]
```

The change for this issue would only require an `import datreant.ex.data.attach` to give everyone the `data` limb. I can imagine persisting a `Bundle` to disk as a simple JSON file, but it would still lack the features of a `Treant` that `Group` has.

**Comment by dotsdl** [comment]
> A bit unrelated thing. What should happen in a forest if two treants have the same key?

I'm not sure I understand the question, but `Treant`s have a uuid that's part of their state file name, and this is unique to each `Treant`. That's how they are distinguished, even if they have the same name (or even the same directory tree, which is possible).

A `Treant` is fundamentally defined by its state file and where that state file lives in the filesystem. If you move the state file, then the `Treant` will still work just fine, but its tree will be the one it now lives in.

**Comment by dotsdl** [comment]
The reason why this member-tracking functionality means we need a `Treant` subclass instead of just a `Limb` attachment is because the information is stored in the state file, which requires new methods for the `TreantFile` class (the `GroupFile` subclass) for manipulating these schema atomically.

Since we're now using JSON as the backend and these map directly to a Python structure, the backend scheme might not have to be so rigid, but that's another can of worms. The backend could probably be a property dict that locks and reads/writes automatically on access; `Limb`s could then directly modify it without having to go through `TreantFile` interface methods. I should stop. :P

**Comment by dotsdl** [comment]
Alright then, moving forward with the [proposal](https://github.com/datreant/datreant/issues/35#issuecomment-172160719). PR incoming soon.

**Comment by dotsdl** [comment]
So I have some bad news. After working to try and get [datreant-data](https://github.com/datreant/datreant-data) and this package to work such that we have

```
datreant
    treants
    collections
    backends
    ex                    # namespace package
        data
```
it turns out that you can only have a namespace package nested within *another* namespace package. Basically, under this scheme `datreant` would need to be a namespace package, which kind of defeats the point. `datreant` could not import any classes or other things directly into its own namespace.

In hindsight this makes sense that it works this way, but I wasn't aware it was a problem. So, given that we wanted to do this federated approach as a namespace package over using a naming convention, we'll do this:

> `datreant` is a namespace module. Core components are within the `datreant.core` package, and any packages that provide additional limbs are added to this namespace, such as `datreant.data`. It is possible to nest namespaces below this in the future. A package like `datreant.data` will not add limbs to any classes on import, but an import like `datreant.data.attach` will.

I've already got this working, and I'm about to push these changes to develop for both `datreant.core` and `datreant.data`. This will allow us to move on to other things. I'll close this issue now, but if anyone isn't happy with this resolution we can open it back up.
