### ISSUE TITLE
datreant.git

### ISSUE THREAD

**Issue by jcfr** [datreant/datreant#82]
In relation to `an API for version controlling a Treant as a git repo` reported on the scipy sprint [document](https://docs.google.com/document/d/15Zhc6LilUrES8sINy7Kasve7imwXDb_XSxv44bjXyz0/edit), may be this package could be useful: https://github.com/tony/libvcs

Also an interesting discussion: https://github.com/tony/libvcs/issues/12

**Comment by dotsdl** [comment]
Awesome @jcfr! I think this could be a great point to start on. I'd expect that VCS functionality in ``datreant`` should be pretty thin, and so we could probably have something working in pretty short order.

**Comment by kain88-de** [comment]
Take a look at git annex and if we can wrap its calls that tool already solved the syncing over ssh and vcs problem.

**Comment by kain88-de** [comment]
@dotsdl how much of vcs should be done? Should there be warnings to activate it for large files?

**Comment by dotsdl** [comment]
Closing as no longer relevant for the project, given its restructuring.
